services:
  api:
    build: .
    container_name: ceish_api
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=ceish_user
      - DB_PASSWORD=ceish_password
      - DB_NAME=ceish_db
      - PORT=3001
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: ceish_postgres
    restart: always
    environment:
      POSTGRES_USER: ceish_user
      POSTGRES_PASSWORD: ceish_password
      POSTGRES_DB: ceish_db
    ports:
      - "3100:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ceish_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ceish.com      # Cambia por tu email de acceso
      PGADMIN_DEFAULT_PASSWORD: admin123           # Cambia por una contraseña segura
    ports:
      - "5051:80"                                  # Acceso web: http://localhost:5050
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: