import { RoleCode } from '../enums/role.enum';
import { Permission } from '../../../../shared/enums/permission.enum';

export const OFFICIAL_ROLE_PRESETS: Record<RoleCode, Permission[]> = {
  [RoleCode.ADMIN_TI]: Object.values(Permission),

  [RoleCode.PRESIDENTE]: [
    Permission.DASHBOARD_RESUMEN,
    Permission.DASHBOARD_NOTIF,
    Permission.DASHBOARD_VENCIMIENTOS,
    Permission.DASHBOARD_SLA,
    Permission.RECEPCION_LISTA,
    Permission.EVALUACION_RIESGO,
    Permission.EVALUACION_ASIGNAR,
    Permission.EVALUACION_EXPEDITA,
    Permission.EVALUACION_PLENO,
    Permission.EVALUACION_SUBSANACIONES,
    Permission.EVALUACION_INFORMES,
    Permission.RESOLUCION_CREAR,
    Permission.RESOLUCION_FIRMAR,
    Permission.RESOLUCION_NOTIF,
    Permission.RESOLUCION_HISTORIAL,
    Permission.RESOLUCION_URGENCIAS,
    Permission.SEGUIMIENTO_AVANCE,
    Permission.SEGUIMIENTO_FINAL,
    Permission.SEGUIMIENTO_ENMIENDAS,
    Permission.SEGUIMIENTO_RENOVACIONES,
    Permission.SEGUIMIENTO_EVENTOS,
    Permission.SEGUIMIENTO_SUSPENSION,
    Permission.USUARIOS_VER,
    Permission.USUARIOS_CONFLICTOS,
    Permission.EVALUADORES_PERFILES,
    Permission.REPORTES_KPIS,
    Permission.REPORTES_TIEMPOS,
    Permission.REPORTES_CARGA,
    Permission.REPORTES_EXPORTAR,
    Permission.REPORTES_AUDITORIA,
  ],

  [RoleCode.SECRETARIA]: [
    Permission.DASHBOARD_RESUMEN,
    Permission.DASHBOARD_NOTIF,
    Permission.DASHBOARD_VENCIMIENTOS,
    Permission.RECEPCION_NUEVO,
    Permission.RECEPCION_LISTA,
    Permission.RECEPCION_VALIDAR,
    Permission.RECEPCION_BUSCAR,
    Permission.RECEPCION_CONSTANCIAS,
    Permission.EVALUACION_SUBSANACIONES,
    Permission.EVALUACION_INFORMES,
    Permission.RESOLUCION_CREAR,
    Permission.RESOLUCION_NOTIF,
    Permission.RESOLUCION_HISTORIAL,
    Permission.SEGUIMIENTO_AVANCE,
    Permission.SEGUIMIENTO_FINAL,
    Permission.SEGUIMIENTO_ENMIENDAS,
    Permission.SEGUIMIENTO_RENOVACIONES,
    Permission.SEGUIMIENTO_EVENTOS,
    Permission.USUARIOS_VER,
    Permission.EVALUADORES_PERFILES,
    Permission.CONFIG_PLANTILLAS,
    Permission.CONFIG_NOTIF,
  ],

  [RoleCode.EVALUADOR]: [
    Permission.DASHBOARD_RESUMEN,
    Permission.DASHBOARD_NOTIF,
    Permission.EVALUACION_EXPEDITA,
    Permission.EVALUACION_PLENO,
    Permission.EVALUACION_INFORMES,
  ],

  [RoleCode.INVESTIGADOR]: [
    Permission.DASHBOARD_RESUMEN,
    Permission.RECEPCION_NUEVO,
    Permission.RECEPCION_LISTA,
    Permission.SEGUIMIENTO_AVANCE,
    Permission.SEGUIMIENTO_FINAL,
    Permission.SEGUIMIENTO_ENMIENDAS,
    Permission.SEGUIMIENTO_RENOVACIONES,
    Permission.SEGUIMIENTO_EVENTOS,
  ],
};
