export enum ReceptionStatus {
  COMPLETO = 'COMPLETO',
  INCOMPLETO = 'INCOMPLETO',
  PENDIENTE_SUBSANACION = 'PENDIENTE_SUBSANACION',
  EN_REVISION_SECRETARIA = 'EN_REVISION_SECRETARIA',
  EVALUACION_SUBSANACIONES = 'EVALUACION_SUBSANACIONES',
}
