export enum RequirementStatus {
  PENDIENTE = 'PENDIENTE',
  PRESENTADO = 'PRESENTADO',
  APROBADO = 'APROBADO',
  RECHAZADO = 'RECHAZADO',
  NO_APLICA = 'NO_APLICA',
  NO_PRESENTADO = 'NO_PRESENTADO',
}
