export enum AgendaSectionType {
  ACTA_ANTERIOR = 'ACTA_ANTERIOR',
  EVALUACION_DICTAMEN = 'EVALUACION_DICTAMEN',
  SEGUIMIENTO_INFORMES = 'SEGUIMIENTO_INFORMES',
  ASUNTOS_VARIOS = 'ASUNTOS_VARIOS',
}

export enum AgendaItemType {
  EVALUACION_INICIAL = 'EVALUACION_INICIAL',
  SUBSANACION = 'SUBSANACION',
  INFORME_INICIO = 'INFORME_INICIO',
  INFORME_AVANCE = 'INFORME_AVANCE',
  INFORME_FIN = 'INFORME_FIN',
}
