export enum Permission {
  // 🏠 DASHBOARD
  DASHBOARD_RESUMEN = 'DASHBOARD_RESUMEN',
  DASHBOARD_NOTIF = 'DASHBOARD_NOTIF',
  DASHBOARD_VENCIMIENTOS = 'DASHBOARD_VENCIMIENTOS',
  DASHBOARD_SLA = 'DASHBOARD_SLA',
  DASHBOARD_VIEW = 'DASHBOARD_RESUMEN', // Alias para compatibilidad

  // 📥 RECEPCIÓN DE PROTOCOLOS
  RECEPCION_NUEVO = 'RECEPCION_NUEVO',
  RECEPCION_LISTA = 'RECEPCION_LISTA',
  RECEPCION_VALIDAR = 'RECEPCION_VALIDAR',
  RECEPCION_BUSCAR = 'RECEPCION_BUSCAR',
  RECEPCION_CONSTANCIAS = 'RECEPCION_CONSTANCIAS',

  // Compatibilidad con controladores antiguos
  RECEPTION_START = 'RECEPCION_NUEVO',
  RECEPTION_VIEW = 'RECEPCION_LISTA',
  RECEPTION_UPLOAD = 'RECEPCION_BUSCAR',
  DOCUMENTS_VALIDATE = 'RECEPCION_VALIDAR',
  DOCUMENTS_APPROVE_FINAL = 'RECEPCION_CONSTANCIAS',

  // ⚖️ EVALUACIÓN ÉTICA
  EVALUACION_RIESGO = 'EVALUACION_RIESGO',
  EVALUACION_ASIGNAR = 'EVALUACION_ASIGNAR',
  EVALUACION_EXPEDITA = 'EVALUACION_EXPEDITA',
  EVALUACION_PLENO = 'EVALUACION_PLENO',
  EVALUACION_SUBSANACIONES = 'EVALUACION_SUBSANACIONES',
  EVALUACION_INFORMES = 'EVALUACION_INFORMES',

  // Compatibilidad con controladores antiguos
  EVALUATORS_SUGGEST = 'EVALUACION_ASIGNAR',
  EVALUATORS_ASSIGN = 'EVALUACION_ASIGNAR',
  EVALUATORS_WORKLOAD_VIEW = 'EVALUACION_RIESGO',
  EVALUATION_FILL = 'EVALUACION_EXPEDITA',
  EVALUATION_VIEW_MINE = 'EVALUACION_PLENO',

  // 📜 RESOLUCIONES
  RESOLUCION_CREAR = 'RESOLUCION_CREAR',
  RESOLUCION_FIRMAR = 'RESOLUCION_FIRMAR',
  RESOLUCION_NOTIF = 'RESOLUCION_NOTIF',
  RESOLUCION_HISTORIAL = 'RESOLUCION_HISTORIAL',
  RESOLUCION_URGENCIAS = 'RESOLUCION_URGENCIAS',

  // Compatibilidad con controladores antiguos
  RESOLUTION_CREATE = 'RESOLUCION_CREAR',
  RESOLUTION_SIGN = 'RESOLUCION_FIRMAR',

  // 🔁 CICLO DE VIDA (SEGUIMIENTO)
  SEGUIMIENTO_AVANCE = 'SEGUIMIENTO_AVANCE',
  SEGUIMIENTO_FINAL = 'SEGUIMIENTO_FINAL',
  SEGUIMIENTO_ENMIENDAS = 'SEGUIMIENTO_ENMIENDAS',
  SEGUIMIENTO_RENOVACIONES = 'SEGUIMIENTO_RENOVACIONES',
  SEGUIMIENTO_EVENTOS = 'SEGUIMIENTO_EVENTOS',
  SEGUIMIENTO_SUSPENSION = 'SEGUIMIENTO_SUSPENSION',

  // 👥 GESTIÓN DE USUARIOS
  USUARIOS_VER = 'USUARIOS_VER',
  PERMISOS_GESTIONAR = 'PERMISOS_GESTIONAR',
  USUARIOS_CONFLICTOS = 'USUARIOS_CONFLICTOS',
  EVALUADORES_PERFILES = 'EVALUADORES_PERFILES',
  AUDITORIA_ACCESOS = 'AUDITORIA_ACCESOS',

  // Compatibilidad con controladores antiguos
  USERS_VIEW = 'USUARIOS_VER',
  USERS_CREATE = 'USUARIOS_VER',
  USERS_EDIT = 'USUARIOS_VER',
  USERS_STATUS_TOGGLE = 'USUARIOS_VER',
  ROLES_ASSIGN = 'PERMISOS_GESTIONAR',
  PERMISSIONS_MANAGE = 'PERMISOS_GESTIONAR',

  // 📊 REPORTES
  REPORTES_KPIS = 'REPORTES_KPIS',
  REPORTES_TIEMPOS = 'REPORTES_TIEMPOS',
  REPORTES_CARGA = 'REPORTES_CARGA',
  REPORTES_EXPORTAR = 'REPORTES_EXPORTAR',
  REPORTES_AUDITORIA = 'REPORTES_AUDITORIA',

  // ⚙️ CONFIGURACIÓN
  CONFIG_CATALOGOS = 'CONFIG_CATALOGOS',
  CONFIG_PLANTILLAS = 'CONFIG_PLANTILLAS',
  CONFIG_NOTIF = 'CONFIG_NOTIF',
  CONFIG_INTEGRACIONES = 'CONFIG_INTEGRACIONES',
  CONFIG_PARAMETROS = 'CONFIG_PARAMETROS',
}
